<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"医生管理",
                        "menuJump":"列表",
                        "tableName":"yisheng"
                    }
                ],
                "menu":"医生管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"护士管理",
                        "menuJump":"列表",
                        "tableName":"hushi"
                    }
                ],
                "menu":"护士管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"病例管理",
                        "menuJump":"列表",
                        "tableName":"bingli"
                    }
                ],
                "menu":"病例管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"床位管理",
                        "menuJump":"列表",
                        "tableName":"chuangwei"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"患者住院房屋管理",
                        "menuJump":"列表",
                        "tableName":"chuangweiBingli"
                    }
                ],
                "menu":"患者住院房屋管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"检查管理",
                        "menuJump":"列表",
                        "tableName":"jiancha"
                    }
                ],
                "menu":"检查管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"医嘱管理",
                        "menuJump":"列表",
                        "tableName":"yizhu"
                    }
                ],
                "menu":"医嘱管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"预付款账户管理",
                        "menuJump":"列表",
                        "tableName":"yufukuan"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"预付款缴费管理",
                        "menuJump":"列表",
                        "tableName":"yufukuanIn"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"消费管理",
                        "menuJump":"列表",
                        "tableName":"xiaofei"
                    }
                ],
                "menu":"金钱管理"
            }
            ,{
                "child":[

                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"检查类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryJiancha"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"科室类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryKeshi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"消费类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryXiaofei"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"医嘱类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryYizhu"
                    }

                ],
                "menu":"基础数据管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"护士管理",
                        "menuJump":"列表",
                        "tableName":"hushi"
                    }
                ],
                "menu":"护士管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"病例管理",
                        "menuJump":"列表",
                        "tableName":"bingli"
                    }
                ],
                "menu":"病例管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"床位管理",
                        "menuJump":"列表",
                        "tableName":"chuangwei"
                    }
					,
					{
                        "buttons":[
                            "查看"
                        ],
                        "menu":"患者住院房屋管理",
                        "menuJump":"列表",
                        "tableName":"chuangweiBingli"
                    }
                ],
                "menu":"床位管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"检查管理",
                        "menuJump":"列表",
                        "tableName":"jiancha"
                    }
                ],
                "menu":"检查管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"医嘱管理",
                        "menuJump":"列表",
                        "tableName":"yizhu"
                    }
                ],
                "menu":"医嘱管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"预付款账户管理",
                        "menuJump":"列表",
                        "tableName":"yufukuan"
                    }
					,
					{
                        "buttons":[
                            "查看"
                        ],
                        "menu":"预付款缴费管理",
                        "menuJump":"列表",
                        "tableName":"yufukuanIn"
                    }
					,
					{
                        "buttons":[
                            "查看"
                        ],
                        "menu":"消费管理",
                        "menuJump":"列表",
                        "tableName":"xiaofei"
                    }
                ],
                "menu":"金钱管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"医生",
        "tableName":"yisheng"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"医生管理",
                        "menuJump":"列表",
                        "tableName":"yisheng"
                    }
                ],
                "menu":"医生管理"
            }
			,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"病例管理",
                        "menuJump":"列表",
                        "tableName":"bingli"
                    }
                ],
                "menu":"病例管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改"
                        ],
                        "menu":"床位管理",
                        "menuJump":"列表",
                        "tableName":"chuangwei"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改"
                        ],
                        "menu":"患者住院房屋管理",
                        "menuJump":"列表",
                        "tableName":"chuangweiBingli"
                    }
                ],
                "menu":"床位管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"检查管理",
                        "menuJump":"列表",
                        "tableName":"jiancha"
                    }
                ],
                "menu":"检查管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"医嘱管理",
                        "menuJump":"列表",
                        "tableName":"yizhu"
                    }
                ],
                "menu":"医嘱管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除"
                        ],
                        "menu":"预付款账户管理",
                        "menuJump":"列表",
                        "tableName":"yufukuan"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"预付款缴费管理",
                        "menuJump":"列表",
                        "tableName":"yufukuanIn"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "删除"
                        ],
                        "menu":"消费管理",
                        "menuJump":"列表",
                        "tableName":"xiaofei"
                    }
                ],
                "menu":"金钱管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"护士",
        "tableName":"hushi"
    }
];

var hasMessage = '';
